### ISSUE TITLE
Entry point is only reached on Wio Lite when leaving DFU mode

### ISSUE THREAD

**Issue by blm768** [riscv-rust/gd32vf103xx-hal#23]
I've been using this crate with a Wio Lite board. Starting with revision [96d24c89944be529a765793eed47ad3f6270242a](https://github.com/riscv-rust/gd32vf103xx-hal/commit/96d24c89944be529a765793eed47ad3f6270242a), the entry function will be executed as expected when I exit DFU mode using the GigaDevice DFU tool. However, after I return the boot switch to its normal position (so it runs the flashed code on reset instead of entering DFU mode) and press the reset button on the board, it seems that the entry function is never executed.

The code in [this repository](https://github.com/blm768/gd32vf103xx-entry-bug) reproduces the issue. When run, it will only light up the LED immediately after leaving DFU mode, not after later resets. If I edit `Cargo.toml` to point to a previous revision of `gd32vf103xx-hal`, such as 567c72cc7d05b25f070bd9ee4db20b4294e44590, the LED will light every time the board is reset.

**Comment by Disasm** [comment]
That's because you're using an old version of `riscv-rt` which doesn't contain a fix. Try version `0.7.0` or newer.

**Comment by blm768** [comment]
Yep; that takes care of it. Thanks!
