### ISSUE TITLE
BlockingI2c does not send ACK after read

### ISSUE THREAD

**Issue by teo3n** [riscv-rust/gd32vf103xx-hal#31]
When trying to read bytes from a slave with .read(), the master never sends an ACK by pulling SDA low after every succesfully byte read. This causes the slave to hang and eventually timeout. The same behaviour is observed with 1 byte reads as well.
As can be seen from the included image, the bahaviour is incorrect and SDA is not pulled low on the 9th clock cycle. Only the data portion of the signal is shown. The data is the same in both images; 0x73.

![Image Pasted at 2020-11-24 23-03](https://user-images.githubusercontent.com/15520494/100191960-bdbdd080-2ef9-11eb-8e7f-62663fee52b8.png)

The issue can be reproduced on a longan nano (GD32VF103) with the following code, with of course a suitable slave device connected and addresses substituted. 

```
    let periph = pac::Peripherals::take().unwrap();
    let mut rcu = periph
        .RCU
        .configure()
        .ext_hf_clock(8.mhz())
        .sysclk(108.mhz())
        .freeze();

    let mut afio = periph.AFIO.constrain(&mut rcu);
    let gpiob = periph.GPIOB.split(&mut rcu);
    let i2c_0 = periph.I2C0;
    let mut delay = McycleDelay::new(&rcu.clocks);
    delay.delay_ms(2);

    let scl = gpiob.pb8.into_alternate_open_drain();
    let sda = gpiob.pb9.into_alternate_open_drain();
    
    let mut i2c_handle = BlockingI2c::i2c0 (
        i2c_0,
        (scl, sda),
        &mut afio,
        Mode::standard(100.khz()),
        &mut rcu,
        998,
        1,
        998,
        998
    );

    let mut read_buf: [u8; 2] = [0; 2];
    let read_status = i2c_handle.read(0x52, &mut read_buf);
```

**Comment by khrs** [comment]
Hi,

Can you please check if this https://github.com/khrs/gd32vf103xx-hal/tree/i2c-fixes branch fixes your issues?

**Comment by teo3n** [comment]
At least on quick glance, everything seems to be working fine and as intended. 
Thanks!
