### ISSUE TITLE
Need to change clock frequency of SPI

### ISSUE THREAD

**Issue by jeancf** [riscv-rust/gd32vf103xx-hal#39]
I am writing a driver for SD card. I need to perform the initialization of the card at 400 KHz max. but when it is done I can push the SPI bus up to 25 MHz.

I set up my SPI interface initially with 400 KHz using `Spi::new()` but then the API does not give me a way to change the prescaler once the SPI struct has been created.

It would make sense to have a `change_clock_freq()` method in `impl<SPI, PINS> Spi<SPI, PINS>` to do that. Would you be OK to merge it if I provided it?

**Comment by Disasm** [comment]
Sounds good! This should be a relatively simple change and easy to review.
