### ISSUE TITLE
Release of 0.5.0

### ISSUE THREAD

**Issue by jeancf** [riscv-rust/gd32vf103xx-hal#45]
Hi there,

I see in CHANGELOG.md that 0.5.0 has a release date of 2021-09-04 but this version is not tagged in the repo and it is not available on crates.io yet. Is it going to be pushed soon?

I am asking because I am interested in the `Spi::change_clock_frequency()` method for a crate that I am getting ready to release.

Thanks.

**Comment by Disasm** [comment]
Oops, probably I was supposed to do this, but no one pinged me. Thank you for the heads-up!

**Comment by Disasm** [comment]
Published v0.5.0.

**Comment by jeancf** [comment]
Perfect, thanks!
Could you also rev the longan-nano crate (to 0.2.1 for example) to update its dependency to version 0.5.0 of this crate? Without it I am getting a "mismatched types" error due to dependency on 2 different versions of the same crate.

**Comment by Disasm** [comment]
Published longan-nano v0.3.0

**Comment by jeancf** [comment]
Thanks a lot!
